[package]
name = "resolve"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.4" }
rand = { version = "0.8" }
hickory-client = { version = "0.24" }
tokio = { version = "1.42", features = ["macros", "time", "net"] }

[lib]
name = "libresolve"
path = "src/lib.rs"
