[package]
name = "render-hex"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5" }
crossbeam = { version = "0.8.4" }
svg = { version = "0.18.0" }

[lib]
name = "lib_renderhex"
