[package]
name = "simple"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = { version = "1.0" }
reqwest = { version = "0.12" }
tokio = { version = "1.42", features = ["macros", "rt-multi-thread"] }
