[package]
name = "serde-eg"
version = "0.1.0"
edition = "2021"

[dependencies]
bincode = { version = "1.3" }
serde = { version = "1.0" }
serde_cbor = { version = "0.11" }
serde_derive = { version = "1.0" }
serde_json = { version = "1.0" }
